title: SANDESH POUDEL
#logo
description: Graduate Research Assistant (PhD), ABE | University of Illinois Urbana Champaign (UIUC) | Robotics & Automation | Computer Vision | Remote Sensing | Artificial Intelligence| Digital Agriculture
#show_downloads: true
theme: jekyll-theme-minimal
