title: SANDESH POUDEL
logo: Ag_Engr.jpg
description: Robotics & Automation | Computer Vision | Remote Sensing | Artificial Intelligence| Digital Agriculture
#show_downloads: true
theme: jekyll-theme-minimal
